/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ramses from "./Ramses";
export type { ramses };
export type { IBooster } from "./IBooster";
export type { IMultiRewards } from "./IMultiRewards";
export type { INeadStake } from "./INeadStake";
export type { IPool } from "./IPool";
export type { IPoolRouter } from "./IPoolRouter";
export type { ISwappoor } from "./ISwappoor";
export type { IVeDepositor } from "./IVeDepositor";
