/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  INeadStake,
  INeadStakeInterface,
} from "../../../contracts/interfaces/INeadStake";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "notifyRewardAmount",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class INeadStake__factory {
  static readonly abi = _abi;
  static createInterface(): INeadStakeInterface {
    return new utils.Interface(_abi) as INeadStakeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): INeadStake {
    return new Contract(address, _abi, signerOrProvider) as INeadStake;
  }
}
