/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IVeDepositor,
  IVeDepositorInterface,
} from "../../../contracts/interfaces/IVeDepositor";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "depositTokens",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "transferFrom",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVeDepositor__factory {
  static readonly abi = _abi;
  static createInterface(): IVeDepositorInterface {
    return new utils.Interface(_abi) as IVeDepositorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVeDepositor {
    return new Contract(address, _abi, signerOrProvider) as IVeDepositor;
  }
}
